In [1]:
import pandas as pd
import unicodedata

In [2]:
# tweet_df = pd.read_csv('Twint_Tweets_2020-11-01_2020-12-01.csv', index_col=0)
tags_df = pd.read_csv('NRC-Emotion-Lexicon.csv', index_col=0)
tags_df

,Spanish (es),Positive,Negative,Anger,Anticipation,Disgust,Fear,Joy,Sadness,Surprise,Trust
English (en),,,,,,,,,,,
aback,detrás,0,0,0,0,0,0,0,0,0,0
abacus,ábaco,0,0,0,0,0,0,0,0,0,1
abandon,abandonar,0,1,0,0,0,1,0,1,0,0
abandoned,abandonado,0,1,1,0,0,1,0,1,0,0
abandonment,abandono,0,1,1,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...
zone,zona,0,0,0,0,0,0,0,0,0,0
zoo,zoo,0,0,0,0,0,0,0,0,0,0
zoological,zoológico,0,0,0,0,0,0,0,0,0,0
zoology,zoología,0,0,0,0,0,0,0,0,0,0
zoom,enfocar,0,0,0,0,0,0,0,0,0,0

In [7]:
def etiquetar(texto):
    pos = 0
    neg = 0
    text = texto.split(",")
    cant = len(text)
    for palabra in text:
        palabra = palabra.replace("'", "");
        palabra = palabra.replace(" ", "");
        palabra = palabra.replace("[", "");
        palabra = palabra.replace("]", "");
        Index_label = tags_df.index[tags_df['Spanish (es)']==palabra].tolist()
        positive = 0
        negative = 0
        for index in Index_label:
            if type(index) == str:
                positive += tags_df['Positive'][index]
                negative += tags_df['Negative'][index]
            else:
                print(index)
        if positive > negative:
            pos += 1
        if negative > positive:
            neg += 1
    return [pos, neg, cant]

sector = ['01','02','03','04','05','06','07','08','09','11','12']
versiones = [2,2,1,1,10,2,1,1,1,1,1]
for i in range(len(sector)):
    if versiones[i] == 1:
        tweet_df = pd.read_csv('Clean_Tweets_' + sector[i] + '.csv', index_col=0)
        tagged_clean = []
        tagged_clean.clear()
        for tweet in tweet_df['clean_tweet']:
            result = etiquetar(tweet)
            tagged_clean.append(result)
        tweet_df['clean_tag'] = tagged_clean
        tagged_clean.clear()
        tagged_lemma = []
        tagged_lemma.clear()
        for tweet in tweet_df['lemma_tweet']:
            result = etiquetar(tweet)
            tagged_lemma.append(result)
        tweet_df['lemma_tag'] = tagged_lemma
        tagged_lemma.clear()
        tweet_df.to_csv('Tagged_Tweets_' + sector[i] + '.csv', index=False, header=True)
    else:
        for j in range(versiones[i]):
            tweet_df = pd.read_csv('Clean_Tweets_' + sector[i] + '_' + str(j+1) + '.csv', index_col=0)
            tagged_clean = []
            tagged_clean.clear()
            for tweet in tweet_df['clean_tweet']:
                result = etiquetar(tweet)
                tagged_clean.append(result)
            tweet_df['clean_tag'] = tagged_clean
            tagged_clean.clear()
            tagged_lemma = []
            tagged_lemma.clear()
            for tweet in tweet_df['lemma_tweet']:
                result = etiquetar(tweet)
                tagged_lemma.append(result)
            tweet_df['lemma_tag'] = tagged_lemma
            tagged_lemma.clear()
            tweet_df.to_csv('Tagged_Tweets_' + sector[i] + '_' + str(j+1) + '.csv', index=False, header=True)

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan